### PR TITLE
Added applications files to this repo

### PR DESCRIPTION
**Pull request by kamaudan**

### CODE REVIEW

**Comment by kamaudan** [comment]
screenshot from 2018-08-30 18-47-40

**Comment by kamaudan** [comment]
screenshot from 2018-08-30 18-50-26

**Comment by kamaudan** [comment]
I ma working to make this look awesome, please comment.

**Comment by jeffnyalik** [comment]
Nice

**Comment by kamaudan** [comment]
Thank you

**Comment by kamaudan** [comment]
Just added a background image

screenshot from 2018-08-30 19-33-21

**Pull request merged**
